# NOTE: update this with your service name
service: serverlessapi

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    tableName: mobiles
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:ap-south-1:455540704641:table/mobiles"

functions:
  create:
    handler: create.main
    events:
      - http:
          path: mobile
          method: post
  get:
    handler: get.main
    events: 
      - http:
          path: mobile/{id}
          method: get
  list:
    handler: list.main
    events: 
      - http:
          path: mobile/{id}
          method: get
  update:
    handler: update.main
    events: 
      - http:
          path: mobile/{id}
          method: put
  delete:
    handler: delete.main
    events: 
      - http:
          path: mobile/{id}
          method: delete
